name: Go

on:

  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: List files in the repository
      run: ls ${{ github.workspace }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - run: echo "Este job terminó con el estado ${{ job.status }}"

